#!/usr/bin/env bash

if [[ ! -d $1 ]]; then
  echo "usage: sync <project-dir>" && exit 1
fi
PROJECT="$1"

run-sync() {
  rsync -i -r --size-only "$@" --exclude-from=.rsync-exclude --delete $PROJECT/ \{\{cookiecutter.repo_name\}\}/
}

# Show what will be done
run-sync --dry-run

read -p "Run sync command (y/n)? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]; then
  echo
  run-sync
fi
